version: 2

models:
  - name: dim_listings_cleansed
    description: Tabla de alojamientos de Airbnb limpiada
    columns:

      - name: listing_id
        description: Id del alojamiento
        data_tests:
          - not_null
          - unique
      
      - name: host_id
        description: Id del anfitrión. Hace referencia a la tabla dim_hosts_cleansed
        data_tests:
          - not_null
          - relationships:
              to: ref('dim_hosts_cleansed')
              field: host_id

      - name: room_type
        description: Tipo de habitación
        data_tests:
          - accepted_values:
              values: ['Entire home/apt', 'Private room', 'Shared room', 'Hotel room']
      
      - name: minimum_nights
        description: '{{ doc("dim_listing_cleansed_minimum_nights") }}'
        data_tests:
          - positive_value

  - name: dim_hosts_cleansed
    description: Tabla de anfitriones de Airbnb limpiada
    columns:

      - name: host_id
        description: Id del anfitrión
        data_tests:
          - not_null
          - unique

      - name: host_name
        description: Nombre del anfitrión
        data_tests:
          - not_null

      - name: is_superhost
        description: Indica si el anfitrión es superhost
        data_tests:
          - not_null

      - name: created_at
        description: Fecha en la que el anfitrión se unió a Airbnb

      - name: updated_at
        description: Fecha en la que el anfitrión actualizó su perfil